import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { ConnectButton } from '@rainbow-me/rainbowkit'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CubeFolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{display:'flex',alignItems:"center",justifyContent:'center', height:'100vh'}}>
        <ConnectButton label='Connect to CubeFolio'/>
      </div>   
      
    </div>
  )
}

export default Home
